name: app

type: php:8.2

runtime:
    extensions:
        - pdo_pgsql
        - apcu
        - mbstring
        - sodium
        - ctype
        - iconv
        - xsl
        

variables:
    php:
#        # uncomment on PHP 7.4+
        opcache.preload: config/preload.php

build:
    flavor: none

disk: 1024

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"



mounts:
    "/var": { source: local, source_path: var }
    "/public/uploads": { source: service, service: files, source_path: uploads }
    

hooks:
    build: |
        set -x -e

        curl -fs https://get.symfony.com/cloud/configurator | bash
        
        NODE_VERSION=18 symfony-build

    deploy: |
        set -x -e

        symfony-deploy

relationships:
    database: "database:postgresql"

crons:
    comment_cleanup:
        # Cleanup every night at 11.50 pm (UTC).
        spec: '50 23 * * *'
        cmd: |
            if [ "$PLATFORM_ENVIRONMENT_TYPE" = "production" ]; then
                croncape symfony console app:comment:cleanup
            fi


workers:
    messenger:
        commands:
            start: symfony console --time-limit=3600 --memory-limit=64M messenger:consume async